# Generated by Django 2.2.1 on 2019-05-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Adress', models.TextField()),
                ('Residence', models.TextField()),
                ('CVID', models.PositiveIntegerField()),
                ('PortfolioID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('QandAID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('AnswerText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('RegistrationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTip',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('IsAnonymous', models.BinaryField()),
                ('Status', models.TextField()),
                ('Time', models.DateTimeField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('PortfolioID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('GoalID', models.AutoField(primary_key=True, serialize=False)),
                ('Deadline', models.DateField()),
                ('Text', models.TextField()),
                ('Status', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CVID',
            fields=[
                ('CVID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('AppointementID', models.AutoField(primary_key=True, serialize=False)),
                ('TimeOfAppointement', models.DateTimeField()),
                ('PlaceOfAppointement', models.TextField()),
                ('Comment', models.TextField()),
                ('Status', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('Status', models.TextField()),
                ('Time', models.DateTimeField()),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionTip')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='AdminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
