# Generated by Django 2.2.1 on 2019-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190614_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='Subjects',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
