# Generated by Django 2.2.1 on 2019-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_portfolio_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='FilledSubjects',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
