# Generated by Django 2.2 on 2019-06-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190619_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointement',
            old_name='PlaceOfAppointement',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='appointement',
            old_name='TimeOfAppointement',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='Text',
            new_name='Description',
        ),
    ]
