# Generated by Django 2.2.1 on 2019-06-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Subjects',
            new_name='Data',
        ),
    ]
