# Generated by Django 2.2.1 on 2019-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_portfolio_filledsubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='Title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='Title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
