# Generated by Django 2.2 on 2019-07-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190626_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('HelpID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.TextField()),
                ('Question', models.TextField()),
                ('UserID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='cvid',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='questiontip',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CVID',
        ),
        migrations.DeleteModel(
            name='QuestionTip',
        ),
    ]
