# Generated by Django 2.2 on 2019-07-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190707_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CVID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='IsAdmin',
        ),
    ]
